CREATE TABLE [dbo].[His_rptRevenueInvoice] (
    [ReportDate]      SMALLDATETIME  NULL,
    [ID]              NVARCHAR (50)  NULL,
    [Invoice_ID]      NVARCHAR (50)  NULL,
    [Inv_Date]        DATETIME       NULL,
    [InvNum]          NVARCHAR (50)  NULL,
    [GuestName]       NVARCHAR (255) NULL,
    [Room]            NVARCHAR (50)  NULL,
    [RoomCharge]      MONEY          DEFAULT ((0)) NULL,
    [Minibar]         MONEY          DEFAULT ((0)) NULL,
    [Laundry]         MONEY          DEFAULT ((0)) NULL,
    [Massage]         MONEY          DEFAULT ((0)) NULL,
    [TelephoneCharge] MONEY          DEFAULT ((0)) NULL,
    [Fax]             MONEY          DEFAULT ((0)) NULL,
    [Restaurant]      MONEY          DEFAULT ((0)) NULL,
    [Orther]          MONEY          DEFAULT ((0)) NULL,
    [TaxService]      MONEY          DEFAULT ((0)) NULL,
    [Total]           MONEY          DEFAULT ((0)) NULL,
    [CashPayment]     MONEY          DEFAULT ((0)) NULL,
    [VAMCPayment]     MONEY          DEFAULT ((0)) NULL,
    [OtherPayment]    MONEY          DEFAULT ((0)) NULL,
    [RoomTypeID]      NVARCHAR (50)  NULL,
    [RoomType_ID]     NVARCHAR (50)  NULL,
    [RoomType]        NVARCHAR (255) NULL,
    [Note]            NVARCHAR (500) NULL,
    [ServiceTypeID]   INT            NULL,
    [fromDate]        SMALLDATETIME  NULL,
    [toDate]          SMALLDATETIME  NULL,
    [Ext]             MONEY          NULL,
    [nDay]            FLOAT (53)     NULL,
    [Price]           MONEY          NULL,
    [Curr]            NVARCHAR (50)  NULL,
    [Room_ID]         NVARCHAR (50)  NULL
);

