CREATE TABLE [dbo].[His_Imports] (
    [s_ID]            NVARCHAR (50)   CONSTRAINT [DF__His_Import__s_ID__16A510BB] DEFAULT (newid()) NOT NULL,
    [s_Import_ID]     NVARCHAR (50)   NULL,
    [i_Item_ID]       NVARCHAR (50)   NULL,
    [dt_ImportDate]   SMALLDATETIME   NULL,
    [s_Object_ID]     NVARCHAR (50)   NULL,
    [s_Object_Name]   NVARCHAR (255)  NULL,
    [s_EmployeeID]    NVARCHAR (50)   NULL,
    [f_VAT]           FLOAT (53)      CONSTRAINT [DF__His_Impor__f_VAT__179934F4] DEFAULT ((0)) NULL,
    [f_Discount]      FLOAT (53)      CONSTRAINT [DF__His_Impor__f_Dis__188D592D] DEFAULT ((0)) NULL,
    [m_Discount]      MONEY           NULL,
    [m_TotalReturn]   MONEY           NULL,
    [m_ImportTotal]   MONEY           CONSTRAINT [DF__His_Impor__m_Imp__19817D66] DEFAULT ((0)) NULL,
    [b_is_Cash]       BIT             CONSTRAINT [DF__His_Impor__b_is___1A75A19F] DEFAULT ((0)) NULL,
    [s_Store_ID]      NVARCHAR (50)   NULL,
    [s_Note]          NVARCHAR (3000) NULL,
    [s_InfoProduct]   NVARCHAR (3000) NULL,
    [s_SymbolInvoice] NVARCHAR (50)   NULL,
    [s_Invoice]       NVARCHAR (50)   NULL,
    [s_Word]          NVARCHAR (500)  NULL,
    [i_IDSort]        NUMERIC (18)    NULL,
    [m_Cost]          MONEY           CONSTRAINT [DF__His_Impor__m_Cos__1B69C5D8] DEFAULT ((0)) NULL,
    [m_Exchange]      MONEY           CONSTRAINT [DF__His_Impor__m_Exc__1C5DEA11] DEFAULT ((0)) NULL,
    [s_Name]          NVARCHAR (255)  NULL,
    [s_Purchase_ID]   NVARCHAR (50)   NULL,
    [dt_Create]       SMALLDATETIME   NULL,
    [dt_LastUpdate]   SMALLDATETIME   NULL,
    [s_UserCreate]    NVARCHAR (50)   NULL,
    [s_UserEdit]      NVARCHAR (50)   NULL,
    [PaymentTermID_s] NVARCHAR (50)   NULL,
    [b_isDept]        BIT             NULL,
    [b_isCash]        BIT             NULL,
    [b_isCashAll]     BIT             NULL,
    [b_isCashPart]    BIT             NULL,
    [b_isCashPrepay]  BIT             NULL,
    [m_Cash]          MONEY           NULL,
    [f_Per]           FLOAT (53)      NULL,
    [m_Per]           MONEY           NULL,
    [s_Char]          NVARCHAR (50)   NULL,
    CONSTRAINT [PK_His_Imports] PRIMARY KEY CLUSTERED ([s_ID] ASC)
);

