CREATE TABLE [dbo].[HisObjects] (
    [EventID]          NVARCHAR (50)  CONSTRAINT [DF_LS_Objects_EventID] DEFAULT (newid()) NOT NULL,
    [s_ID]             NVARCHAR (50)  NOT NULL,
    [s_Object_ID]      NVARCHAR (50)  NULL,
    [s_Name]           NVARCHAR (255) NULL,
    [s_Address]        NVARCHAR (500) NULL,
    [s_District_ID]    NVARCHAR (50)  NULL,
    [s_Phone1]         NVARCHAR (50)  NULL,
    [s_Phone2]         NVARCHAR (50)  NULL,
    [s_Fax]            NVARCHAR (50)  NULL,
    [s_Email]          NVARCHAR (100) NULL,
    [s_Website]        NVARCHAR (100) NULL,
    [s_TaxNo]          NVARCHAR (50)  NULL,
    [s_ObjectGroup_ID] NVARCHAR (50)  NULL,
    [s_Employee_ID]    NVARCHAR (50)  NULL,
    [b_Customer]       BIT            CONSTRAINT [DF_His_Objects_b_Customer] DEFAULT ((0)) NULL,
    [b_Supplier]       BIT            CONSTRAINT [DF_His_Objects_b_Supplier] DEFAULT ((0)) NULL,
    [m_FirstIncome]    MONEY          CONSTRAINT [DF_His_Objects_m_FirstIncome] DEFAULT ((0)) NULL,
    [m_FirstOutcome]   MONEY          CONSTRAINT [DF_His_Objects_m_FirstOutcome] DEFAULT ((0)) NULL,
    [m_CurIncome]      MONEY          CONSTRAINT [DF_His_Objects_m_CurIncome] DEFAULT ((0)) NULL,
    [m_CurOutcome]     MONEY          CONSTRAINT [DF_His_Objects_m_CurOutcome] DEFAULT ((0)) NULL,
    [m_PrepayCus]      MONEY          CONSTRAINT [DF_His_Objects_m_PrepayCus] DEFAULT ((0)) NULL,
    [m_PrepaySup]      MONEY          CONSTRAINT [DF_His_Objects_m_PrepaySup] DEFAULT ((0)) NULL,
    [s_Note]           NVARCHAR (500) NULL,
    [i_Ordinal]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [b_valid]          BIT            CONSTRAINT [DF_His_Objects_b_valid] DEFAULT ((1)) NULL,
    [s_Currency]       NVARCHAR (50)  NULL,
    [i_Payment]        INT            NULL,
    [s_PaymentTerm]    NVARCHAR (50)  NULL,
    [m_DebtLimit]      MONEY          NULL,
    [f_Discount]       FLOAT (53)     NULL,
    [s_PriceLevel_ID]  NVARCHAR (50)  NULL,
    [s_UserCreate]     NVARCHAR (50)  NULL,
    [dt_Create]        SMALLDATETIME  NULL,
    [s_UserEdit]       NVARCHAR (50)  NULL,
    [dt_LastUpdate]    SMALLDATETIME  NULL,
    [Passport]         NVARCHAR (50)  NULL,
    [dtCreatePassport] SMALLDATETIME  NULL,
    [dtBirthday]       SMALLDATETIME  NULL,
    [Posion]           NVARCHAR (50)  NULL,
    [Male]             INT            CONSTRAINT [DF_His_Objects_Male] DEFAULT ((0)) NULL,
    [Visa]             NVARCHAR (50)  NULL,
    [dtVisa]           SMALLDATETIME  NULL,
    [dtFrom]           SMALLDATETIME  NULL,
    [timeFrom]         SMALLDATETIME  NULL,
    [dtTo]             SMALLDATETIME  NULL,
    [timeTo]           SMALLDATETIME  NULL,
    [Company]          NVARCHAR (255) NULL,
    [AddressCompany]   NVARCHAR (255) NULL,
    [Nation_ID]        NVARCHAR (50)  NULL,
    [Mark_ID]          INT            NULL,
    [BorderGate_ID]    INT            NULL,
    [TravelPermit]     NVARCHAR (255) NULL,
    CONSTRAINT [PK_His_Objects] PRIMARY KEY CLUSTERED ([s_ID] ASC)
);

