CREATE TABLE [dbo].[HisPR_Booking] (
    [Event_ID]    NVARCHAR (50)   CONSTRAINT [DF_HisPR_Booking_Event_ID] DEFAULT (newid()) NOT NULL,
    [s_ID]        NVARCHAR (50)   NOT NULL,
    [BK_Date]     SMALLDATETIME   NULL,
    [FullName]    NVARCHAR (255)  NULL,
    [Contact]     NVARCHAR (255)  NULL,
    [Company]     NVARCHAR (255)  NULL,
    [Address]     NVARCHAR (255)  NULL,
    [PhoneOffice] NVARCHAR (50)   NULL,
    [HomePhone]   NVARCHAR (50)   NULL,
    [From_date]   SMALLDATETIME   NULL,
    [To_date]     SMALLDATETIME   NULL,
    [Note]        NVARCHAR (1024) NULL,
    [isArrange]   BIT             NULL,
    [isReg]       BIT             NULL,
    [Payment]     INT             NULL,
    [CaLV]        NVARCHAR (50)   NULL,
    [Nguoidat]    NVARCHAR (255)  NULL,
    [Dienthoai]   NVARCHAR (50)   NULL,
    [Fax]         NVARCHAR (50)   NULL,
    [DatCoc]      MONEY           NULL,
    [Partner_ID]  NVARCHAR (50)   NULL,
    [UCreate]     NVARCHAR (50)   NULL,
    [dtCreate]    SMALLDATETIME   NULL,
    [UEdit]       NVARCHAR (50)   NULL,
    [dtEdit]      SMALLDATETIME   NULL,
    [IDSort]      NUMERIC (18)    NULL,
    [Curr]        NVARCHAR (50)   NULL,
    [CardID]      NVARCHAR (50)   NULL,
    [CardSerial]  NVARCHAR (50)   NULL,
    [Number_ID]   NVARCHAR (50)   NULL,
    [isLate]      BIT             NULL,
    [Adult]       INT             DEFAULT ((0)) NULL,
    [Child]       INT             DEFAULT ((0)) NULL,
    [SegmID]      INT             NULL,
    [NoShow]      BIT             NULL,
    CONSTRAINT [PK_HisPR_Booking_1] PRIMARY KEY CLUSTERED ([s_ID] ASC),
    CONSTRAINT [FK_HisPR_Booking_PR_Events] FOREIGN KEY ([Event_ID]) REFERENCES [dbo].[PR_Events] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

