CREATE TABLE [dbo].[HisPr_ResOrder] (
    [EventID]      NVARCHAR (50)  CONSTRAINT [DF_HisResOrder_EventID] DEFAULT (newid()) NOT NULL,
    [s_ID]         NVARCHAR (50)  NULL,
    [Issue_ID]     NVARCHAR (50)  NULL,
    [PPV]          FLOAT (53)     NULL,
    [Vat]          FLOAT (53)     NULL,
    [Curr]         NVARCHAR (50)  NULL,
    [Order_day]    SMALLDATETIME  NULL,
    [Payment]      INT            NULL,
    [Sub_Total]    MONEY          NULL,
    [MsVat]        NVARCHAR (50)  NULL,
    [Company]      NVARCHAR (50)  NULL,
    [RedBill]      BIT            NOT NULL,
    [isCheckOut]   BIT            CONSTRAINT [DF_HisResOrder_isCheckOut] DEFAULT ((0)) NULL,
    [Inwords]      NVARCHAR (100) NULL,
    [Register_ID]  NVARCHAR (50)  NULL,
    [Employee_ID]  NVARCHAR (50)  NULL,
    [IsBills]      BIT            NULL,
    [Service_ID]   INT            NULL,
    [CaLV]         NVARCHAR (50)  NULL,
    [SoHD]         NVARCHAR (50)  NULL,
    [SoHieuHD]     NVARCHAR (50)  NULL,
    [UCreate]      NVARCHAR (50)  NULL,
    [dtCreate]     SMALLDATETIME  NULL,
    [UEdit]        NVARCHAR (50)  NULL,
    [dtEdit]       SMALLDATETIME  NULL,
    [IDSort]       NUMERIC (18)   NULL,
    [TaxTTDB]      FLOAT (53)     NULL,
    [TaxOther]     FLOAT (53)     NULL,
    [Sub_TotalVAT] MONEY          NULL,
    [isTax]        BIT            NULL,
    [CardID]       NVARCHAR (50)  NULL,
    [CardSerial]   NVARCHAR (50)  NULL,
    [Object_Name]  NVARCHAR (255) NULL,
    [Address]      NVARCHAR (255) NULL,
    [Phone]        NVARCHAR (20)  NULL,
    [Fax]          NVARCHAR (20)  NULL,
    [RegOld]       NVARCHAR (50)  NULL,
    [IsFolio]      BIT            NULL,
    [Area_ID]      NVARCHAR (50)  NULL,
    [Origin_ID]    NVARCHAR (50)  NULL,
    [Note]         NVARCHAR (255) NULL,
    CONSTRAINT [PK_HisResOrder] PRIMARY KEY CLUSTERED ([EventID] ASC)
);

