CREATE TABLE [dbo].[Ls_DanhsachHD] (
    [s_ID]         NVARCHAR (50)  NOT NULL,
    [SoHD]         NVARCHAR (50)  NULL,
    [SoHieuHD]     NVARCHAR (50)  NULL,
    [Object_ID]    NVARCHAR (50)  NULL,
    [PayMent]      NVARCHAR (50)  NULL,
    [Object_Name]  NVARCHAR (255) NULL,
    [Address]      NVARCHAR (255) NULL,
    [Company]      NVARCHAR (255) NULL,
    [MST]          NVARCHAR (50)  NULL,
    [Fax]          NVARCHAR (50)  NULL,
    [Phone]        NVARCHAR (50)  NULL,
    [CreateDate]   SMALLDATETIME  NULL,
    [NgayHoadon]   SMALLDATETIME  NULL,
    [STT]          INT            NULL,
    [Note]         NVARCHAR (255) NULL,
    [VAT]          FLOAT (53)     NULL,
    [TotalNoneTax] MONEY          NULL,
    [TotalTax]     MONEY          NULL,
    [IsPrint]      BIT            NULL,
    [nPrint]       INT            NULL,
    [IsDel]        BIT            NULL,
    [DateDel]      SMALLDATETIME  NULL,
    [Inwords]      NVARCHAR (255) NULL,
    [OrderID]      NVARCHAR (50)  NULL,
    [UserCreate]   NVARCHAR (50)  NULL,
    [UserEdit]     NVARCHAR (50)  NULL,
    [dtEdit]       SMALLDATETIME  NULL,
    [s1]           NVARCHAR (1)   NULL,
    [s2]           NVARCHAR (1)   NULL,
    [s3]           NVARCHAR (1)   NULL,
    [s4]           NVARCHAR (1)   NULL,
    [s5]           NVARCHAR (1)   NULL,
    [s6]           NVARCHAR (1)   NULL,
    [s7]           NVARCHAR (1)   NULL,
    [s8]           NVARCHAR (1)   NULL,
    [s9]           NVARCHAR (1)   NULL,
    [s10]          NVARCHAR (1)   NULL,
    [s11]          NVARCHAR (1)   NULL,
    [s12]          NVARCHAR (1)   NULL,
    [s13]          NVARCHAR (1)   NULL,
    [s14]          NVARCHAR (1)   NULL,
    PRIMARY KEY CLUSTERED ([s_ID] ASC)
);

