CREATE TABLE [dbo].[Ls_Orders_2010_1] (
    [s_ID]                  NVARCHAR (50)   DEFAULT (newid()) NOT NULL,
    [s_Order_ID]            NVARCHAR (50)   NULL,
    [s_Char]                NVARCHAR (50)   NULL,
    [i_ItemID]              NVARCHAR (50)   NULL,
    [dt_OrderDate]          SMALLDATETIME   NULL,
    [s_EmployeeID]          NVARCHAR (50)   NULL,
    [s_ObjectID]            NVARCHAR (50)   NULL,
    [s_DeliverableAddresss] NVARCHAR (500)  NULL,
    [s_PayabbleAddress]     NVARCHAR (500)  NULL,
    [s_ContactID]           NVARCHAR (50)   NULL,
    [m_Ordertotal]          MONEY           DEFAULT ((0)) NULL,
    [s_Note]                NVARCHAR (4000) NULL,
    [f_VAT]                 FLOAT (53)      DEFAULT ((0)) NULL,
    [m_VAT]                 MONEY           DEFAULT ((0)) NULL,
    [f_Discount]            FLOAT (53)      DEFAULT ((0)) NULL,
    [m_OrderTotalDiscount]  MONEY           DEFAULT ((0)) NULL,
    [f_Per]                 FLOAT (53)      DEFAULT ((0)) NULL,
    [m_Per]                 MONEY           DEFAULT ((0)) NULL,
    [i_IDSort]              NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [s_Word]                NVARCHAR (500)  NULL,
    [s_GroupProduct]        NVARCHAR (3000) NULL,
    [s_FullOrderDate]       NVARCHAR (50)   DEFAULT (getdate()) NULL,
    [s_SymbolInvoice]       NVARCHAR (50)   NULL,
    [s_Invoice]             NVARCHAR (50)   NULL,
    [m_Exchange]            MONEY           DEFAULT ((0)) NULL,
    [s_PurchaseID]          NVARCHAR (50)   NULL,
    [s_Quote_ID]            NVARCHAR (50)   NULL,
    [b_isDiscount]          BIT             DEFAULT ((0)) NULL,
    [b_isDiscountProduct]   BIT             DEFAULT ((0)) NULL,
    [i_TermID]              NVARCHAR (50)   NULL,
    [s_Creator]             NVARCHAR (50)   NULL,
    [s_Editor]              NVARCHAR (50)   NULL,
    [dt_Create]             SMALLDATETIME   NULL,
    [dt_Edit]               SMALLDATETIME   NULL,
    [f_Commission]          FLOAT (53)      DEFAULT ((0)) NULL,
    [m_Commission]          MONEY           DEFAULT ((0)) NULL,
    [b_isDept]              BIT             DEFAULT ((0)) NULL,
    [b_isCash]              BIT             DEFAULT ((0)) NULL,
    [b_isCashAll]           BIT             DEFAULT ((0)) NULL,
    [b_isCashPart]          BIT             DEFAULT ((0)) NULL,
    [b_isCashPrepay]        BIT             DEFAULT ((0)) NULL,
    [m_Cash]                MONEY           DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([s_ID] ASC),
    CONSTRAINT [FK_Ls_Orders_2010_1_LS_Objects] FOREIGN KEY ([s_ObjectID]) REFERENCES [dbo].[LS_Objects] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

