CREATE TABLE [dbo].[Ls_SplitBill] (
    [s_ID]             NVARCHAR (50)  CONSTRAINT [DF_Ls_SplitBill_s_ID] DEFAULT (newid()) NOT NULL,
    [OriginOrderID]    NVARCHAR (50)  CONSTRAINT [DF_Table_1_s_ID] DEFAULT (newid()) NULL,
    [NumberID]         NVARCHAR (50)  NULL,
    [dayMonth]         SMALLDATETIME  NULL,
    [ObjectID]         NVARCHAR (50)  NULL,
    [ObjectName]       NVARCHAR (255) NULL,
    [Address]          NVARCHAR (255) NULL,
    [Company]          NVARCHAR (255) NULL,
    [ComAddress]       NVARCHAR (255) NULL,
    [Phone]            NVARCHAR (50)  NULL,
    [Fax]              NVARCHAR (50)  NULL,
    [TaxCode]          NVARCHAR (50)  NULL,
    [VAT]              FLOAT (53)     NULL,
    [TaxTTDB]          FLOAT (53)     NULL,
    [TaxOther]         FLOAT (53)     NULL,
    [Serv]             FLOAT (53)     NULL,
    [PerDiscount]      FLOAT (53)     NULL,
    [MoneyDiscount]    MONEY          NULL,
    [Payment]          INT            NULL,
    [Register_ID]      NVARCHAR (50)  NULL,
    [Curr]             NVARCHAR (50)  CONSTRAINT [DF_Ls_SplitBill_Curr] DEFAULT (N'VND') NULL,
    [Exchange]         FLOAT (53)     NULL,
    [Table_ID]         NVARCHAR (50)  NULL,
    [Sub_TotalVND]     MONEY          NULL,
    [Sub_TotalUSD]     MONEY          NULL,
    [Sub_TotalTaxVND]  MONEY          NULL,
    [Sub_TotalTaxUSD]  MONEY          NULL,
    [Inwords]          NVARCHAR (255) NULL,
    [Note]             NVARCHAR (255) NULL,
    [IDSort]           NUMERIC (18)   NULL,
    [Issue_ID]         NVARCHAR (50)  NULL,
    [Employee_ID]      NVARCHAR (50)  NULL,
    [VIP]              BIT            CONSTRAINT [DF_Ls_SplitBill_VIP] DEFAULT ((0)) NULL,
    [PerVIP]           FLOAT (53)     NULL,
    [Free]             BIT            CONSTRAINT [DF_Ls_SplitBill_Free] DEFAULT ((0)) NULL,
    [SoHD]             NVARCHAR (50)  NULL,
    [SohieuHD]         NVARCHAR (50)  NULL,
    [TypeCard]         NVARCHAR (50)  NULL,
    [CardSerial]       NVARCHAR (50)  NULL,
    [Deposit_ID]       NVARCHAR (50)  NULL,
    [Deposit]          MONEY          NULL,
    [OrderID_Res]      NVARCHAR (50)  NULL,
    [NumPers]          INT            NULL,
    [dtCreate]         SMALLDATETIME  NULL,
    [dtEdit]           SMALLDATETIME  NULL,
    [UCreate]          NVARCHAR (50)  NULL,
    [UEdit]            NVARCHAR (50)  NULL,
    [Cashier_ID]       NVARCHAR (50)  NULL,
    [Shift_ID]         NVARCHAR (50)  NULL,
    [isDebt]           BIT            NULL,
    [ObjID_VAT]        NVARCHAR (50)  NULL,
    [ObjName_VAT]      NVARCHAR (255) NULL,
    [RoomNo]           NVARCHAR (50)  NULL,
    [VAT_Amount]       MONEY          NULL,
    [TTDB_Amount]      MONEY          NULL,
    [PPV_Amount]       MONEY          NULL,
    [TaxOther_Amount]  MONEY          NULL,
    [Bank_ID]          NVARCHAR (50)  NULL,
    [MCash]            MONEY          NULL,
    [MCard]            MONEY          NULL,
    [MTransfer]        MONEY          NULL,
    [MDebt]            MONEY          NULL,
    [MGotoRep]         MONEY          NULL,
    [TotalNoneTax]     MONEY          NULL,
    [mDiscountProduct] MONEY          NULL,
    [iDisOpt]          INT            NULL,
    [fDisOfFood]       FLOAT (53)     NULL,
    [fDisOfDrink]      FLOAT (53)     NULL,
    [CurrPay]          NVARCHAR (50)  NULL,
    [ExCurrPay]        FLOAT (53)     NULL,
    [MOut]             FLOAT (53)     NULL,
    [dtUpdated]        SMALLDATETIME  NULL,
    [iType]            INT            NULL,
    [ObjVATID]         NVARCHAR (50)  NULL,
    [ObjVATName]       NVARCHAR (255) NULL,
    [InvoiceSymbol]    NVARCHAR (50)  NULL,
    [InvoiceNumber]    NVARCHAR (50)  NULL,
    [MaSoThue]         NVARCHAR (50)  NULL,
    [InvoiceDate]      SMALLDATETIME  NULL,
    CONSTRAINT [PK_Ls_SplitBill] PRIMARY KEY CLUSTERED ([s_ID] ASC)
);

