CREATE TABLE [dbo].[PR_BKDetail_Res] (
    [s_ID]                  NVARCHAR (50)  DEFAULT (newid()) NOT NULL,
    [OrderID]               NVARCHAR (50)  NULL,
    [Product_ID]            NVARCHAR (50)  NULL,
    [ProductID]             NVARCHAR (50)  NULL,
    [Product_Name]          NVARCHAR (255) NULL,
    [isProduct]             BIT            DEFAULT ((1)) NULL,
    [Unit]                  NVARCHAR (50)  NULL,
    [Qty]                   FLOAT (53)     NULL,
    [Exchange]              FLOAT (53)     DEFAULT ((1)) NULL,
    [Price]                 MONEY          NULL,
    [Discount]              FLOAT (53)     NULL,
    [Store_ID]              NVARCHAR (50)  NULL,
    [IDSort]                NUMERIC (18)   NULL,
    [Note]                  NVARCHAR (255) NULL,
    [VAT]                   FLOAT (53)     NULL,
    [VAT_Amount]            MONEY          NULL,
    [PPV]                   FLOAT (53)     NULL,
    [PPV_Amount]            MONEY          NULL,
    [EndPrice]              MONEY          NULL,
    [b_isServices]          BIT            NULL,
    [iState]                INT            NULL,
    [TTDB]                  FLOAT (53)     NULL,
    [TTDB_Amount]           MONEY          NULL,
    [NK]                    FLOAT (53)     NULL,
    [NK_Amount]             MONEY          NULL,
    [OtherTax]              FLOAT (53)     NULL,
    [OtherTax_Amount]       MONEY          NULL,
    [isTax]                 BIT            NULL,
    [mDiscount]             MONEY          NULL,
    [f_DiscountNumber]      FLOAT (53)     NULL,
    [m_DiscountNumber]      MONEY          NULL,
    [SubTotal]              MONEY          NULL,
    [SubTotalNoneDisNumber] MONEY          NULL,
    PRIMARY KEY CLUSTERED ([s_ID] ASC),
    CONSTRAINT [FK_PR_BKDetail_Res_PR_ResBooking] FOREIGN KEY ([OrderID]) REFERENCES [dbo].[PR_ResBooking] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

