CREATE TABLE [dbo].[PR_Register] (
    [Group_ID]       NVARCHAR (50)  NULL,
    [BK_ID]          NVARCHAR (50)  NULL,
    [s_ID]           NVARCHAR (50)  CONSTRAINT [DF__PR_Registe__s_ID__3469B275] DEFAULT (newid()) NOT NULL,
    [Object_ID]      NVARCHAR (50)  NOT NULL,
    [Room_ID]        NVARCHAR (50)  NOT NULL,
    [PreRoom_ID]     NVARCHAR (50)  NULL,
    [From_date]      SMALLDATETIME  NULL,
    [To_date]        SMALLDATETIME  NULL,
    [CheckOut_Date]  SMALLDATETIME  NULL,
    [Price]          MONEY          NULL,
    [Serv]           FLOAT (53)     NULL,
    [Curr]           NVARCHAR (50)  NULL,
    [Discount]       FLOAT (53)     NULL,
    [Stat]           NVARCHAR (50)  NULL,
    [Pers]           SMALLINT       NULL,
    [Price_Extra]    MONEY          NULL,
    [Vat]            FLOAT (53)     NULL,
    [Payment]        INT            NULL,
    [TravelPermit]   NVARCHAR (50)  NULL,
    [Descr]          NVARCHAR (255) NULL,
    [CaLV]           NVARCHAR (50)  NULL,
    [PreRegister_ID] NVARCHAR (50)  NULL,
    [IsRegDay]       BIT            NULL,
    [DisMoney]       MONEY          NULL,
    [IDSort]         NUMERIC (18)   NOT NULL,
    [ObjectType_ID]  NVARCHAR (50)  NULL,
    [UCreate]        NVARCHAR (50)  NULL,
    [dtCreate]       SMALLDATETIME  NULL,
    [UEdit]          NVARCHAR (50)  NULL,
    [dtEdit]         SMALLDATETIME  NULL,
    [Note]           NVARCHAR (255) NULL,
    [b_Insert]       BIT            CONSTRAINT [DF_PR_Register_b_Insert] DEFAULT ((0)) NULL,
    [tmpToDate]      SMALLDATETIME  NULL,
    [BKArrange_ID]   NVARCHAR (50)  NULL,
    [CardID]         NVARCHAR (50)  NULL,
    [CardSerial]     NVARCHAR (50)  NULL,
    [Child]          INT            DEFAULT ((0)) NULL,
    [SegmID]         INT            NULL,
    [LimitID]        NVARCHAR (50)  NULL,
    [m_Balance]      MONEY          NULL,
    [Partner_ID]     NVARCHAR (50)  NULL,
    [listObjReg]     NVARCHAR (500) NULL,
    [IsMonth]        BIT            NULL,
    CONSTRAINT [PK_PR_Register] PRIMARY KEY CLUSTERED ([s_ID] ASC),
    CONSTRAINT [FK_PR_Register_Ls_ObjectType] FOREIGN KEY ([ObjectType_ID]) REFERENCES [dbo].[Ls_ObjectType] ([s_ID]) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT [FK_PR_Register_Ls_Partner] FOREIGN KEY ([Partner_ID]) REFERENCES [dbo].[Ls_Partner] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PR_Register_Ls_PaymentDebt] FOREIGN KEY ([Payment]) REFERENCES [dbo].[Ls_PaymentDebt] ([i_ID]) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT [FK_PR_Register_Ls_Room] FOREIGN KEY ([Room_ID]) REFERENCES [dbo].[Ls_Room] ([s_ID]) ON UPDATE CASCADE,
    CONSTRAINT [FK_PR_Register_PR_RegisterGroup] FOREIGN KEY ([Group_ID]) REFERENCES [dbo].[PR_RegisterGroup] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

