CREATE TABLE [dbo].[PR_ResBooking] (
    [s_ID]           NVARCHAR (50)  CONSTRAINT [DF_PR_ResBooking_s_ID] DEFAULT (newid()) NOT NULL,
    [NumberID]       NVARCHAR (50)  NULL,
    [dayMonth]       SMALLDATETIME  NULL,
    [ObjectName]     NVARCHAR (255) NULL,
    [Address]        NVARCHAR (255) NULL,
    [Phone]          NVARCHAR (50)  NULL,
    [Company]        NVARCHAR (255) NULL,
    [Deposit]        MONEY          NULL,
    [nTable]         INT            NULL,
    [ContactName]    NVARCHAR (255) NULL,
    [AddressContact] NVARCHAR (255) NULL,
    [PhoneContact]   NVARCHAR (50)  NULL,
    [dtCreate]       SMALLDATETIME  NULL,
    [dtEdit]         SMALLDATETIME  NULL,
    [UCreate]        NVARCHAR (50)  NULL,
    [UEdit]          NVARCHAR (50)  NULL,
    [Note]           NVARCHAR (255) NULL,
    [Ordinal]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [Stat]           BIT            CONSTRAINT [DF_PR_ResBooking_Stat] DEFAULT ((1)) NULL,
    [Curr]           NVARCHAR (50)  NULL,
    [isIndicated]    BIT            CONSTRAINT [DF__PR_ResBoo__isInd__0075D87A] DEFAULT ((0)) NULL,
    [Shift_ID]       NVARCHAR (50)  NULL,
    [Cashier_ID]     NVARCHAR (50)  NULL,
    [Employee_ID]    NVARCHAR (50)  NULL,
    [Noiphathanh]    NVARCHAR (50)  NULL,
    [Adult]          INT            NULL,
    [Child]          INT            NULL,
    [State]          INT            NULL,
    [ReasonCancel]   NVARCHAR (255) NULL,
    [ObjectID]       NVARCHAR (50)  NULL,
    [TableID]        NVARCHAR (50)  NULL,
    [SubTotal]       MONEY          NULL,
    CONSTRAINT [PK_PR_ResBooking] PRIMARY KEY CLUSTERED ([s_ID] ASC)
);

