CREATE TABLE [dbo].[PR_WorkersNew] (
    [s_ID]          NVARCHAR (50)  DEFAULT (newid()) NOT NULL,
    [s_Employee_ID] NVARCHAR (50)  NULL,
    [i_Year]        INT            NULL,
    [i_Month]       INT            NULL,
    [s_Shift_ID]    NVARCHAR (50)  NULL,
    [s_Note]        NVARCHAR (255) NULL,
    [D1]            NVARCHAR (5)   NULL,
    [D2]            NVARCHAR (5)   NULL,
    [D3]            NVARCHAR (5)   NULL,
    [D4]            NVARCHAR (5)   NULL,
    [D5]            NVARCHAR (5)   NULL,
    [D6]            NVARCHAR (5)   NULL,
    [D7]            NVARCHAR (5)   NULL,
    [D8]            NVARCHAR (5)   NULL,
    [D9]            NVARCHAR (5)   NULL,
    [D10]           NVARCHAR (5)   NULL,
    [D11]           NVARCHAR (5)   NULL,
    [D12]           NVARCHAR (5)   NULL,
    [D13]           NVARCHAR (5)   NULL,
    [D14]           NVARCHAR (5)   NULL,
    [D15]           NVARCHAR (5)   NULL,
    [D16]           NVARCHAR (5)   NULL,
    [D17]           NVARCHAR (5)   NULL,
    [D18]           NVARCHAR (5)   NULL,
    [D19]           NVARCHAR (5)   NULL,
    [D20]           NVARCHAR (5)   NULL,
    [D21]           NVARCHAR (5)   NULL,
    [D22]           NVARCHAR (5)   NULL,
    [D23]           NVARCHAR (5)   NULL,
    [D24]           NVARCHAR (5)   NULL,
    [D25]           NVARCHAR (5)   NULL,
    [D26]           NVARCHAR (5)   NULL,
    [D27]           NVARCHAR (5)   NULL,
    [D28]           NVARCHAR (5)   NULL,
    [D29]           NVARCHAR (5)   NULL,
    [D30]           NVARCHAR (5)   NULL,
    [D31]           NVARCHAR (5)   NULL,
    PRIMARY KEY CLUSTERED ([s_ID] ASC),
    CONSTRAINT [FK_PR_WorkersNew_LS_Employees] FOREIGN KEY ([s_Employee_ID]) REFERENCES [dbo].[LS_Employees] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

