CREATE TABLE [dbo].[PR_Workers] (
    [s_ID]          NVARCHAR (50)  CONSTRAINT [DF_PR_Workers_s_ID] DEFAULT (newid()) NOT NULL,
    [s_Employee_ID] NVARCHAR (50)  NULL,
    [i_Year]        INT            NULL,
    [i_Month]       INT            NULL,
    [s_Shift_ID]    NVARCHAR (50)  NULL,
    [s_Note]        NVARCHAR (255) NULL,
    [D1]            NVARCHAR (5)   NULL,
    [D2]            NVARCHAR (5)   NULL,
    [D3]            NVARCHAR (5)   NULL,
    [D4]            NVARCHAR (5)   NULL,
    [D5]            NVARCHAR (5)   NULL,
    [D6]            NVARCHAR (5)   NULL,
    [D7]            NVARCHAR (5)   NULL,
    [D8]            NVARCHAR (5)   NULL,
    [D9]            NVARCHAR (5)   NULL,
    [D10]           NVARCHAR (5)   NULL,
    [D11]           NVARCHAR (5)   NULL,
    [D12]           NVARCHAR (5)   NULL,
    [D13]           NVARCHAR (5)   NULL,
    [D14]           NVARCHAR (5)   NULL,
    [D15]           NVARCHAR (5)   NULL,
    [D16]           NVARCHAR (5)   NULL,
    [D17]           NVARCHAR (5)   NULL,
    [D18]           NVARCHAR (5)   NULL,
    [D19]           NVARCHAR (5)   NULL,
    [D20]           NVARCHAR (5)   NULL,
    [D21]           NVARCHAR (5)   NULL,
    [D22]           NVARCHAR (5)   NULL,
    [D23]           NVARCHAR (5)   NULL,
    [D24]           NVARCHAR (5)   NULL,
    [D25]           NVARCHAR (5)   NULL,
    [D26]           NVARCHAR (5)   NULL,
    [D27]           NVARCHAR (5)   NULL,
    [D28]           NVARCHAR (5)   NULL,
    [D29]           NVARCHAR (5)   NULL,
    [D30]           NVARCHAR (5)   NULL,
    [D31]           NVARCHAR (5)   NULL,
    [s_Note_1]      NVARCHAR (255) NULL,
    [s_Note_2]      NVARCHAR (255) NULL,
    [s_Note_3]      NVARCHAR (255) NULL,
    [s_Note_4]      NVARCHAR (255) NULL,
    [s_Note_5]      NVARCHAR (255) NULL,
    [s_Note_6]      NVARCHAR (255) NULL,
    [s_Note_7]      NVARCHAR (255) NULL,
    [s_Note_8]      NVARCHAR (255) NULL,
    [s_Note_9]      NVARCHAR (255) NULL,
    [s_Note_10]     NVARCHAR (255) NULL,
    [s_Note_11]     NVARCHAR (255) NULL,
    [s_Note_12]     NVARCHAR (255) NULL,
    [s_Note_13]     NVARCHAR (255) NULL,
    [s_Note_14]     NVARCHAR (255) NULL,
    [s_Note_15]     NVARCHAR (255) NULL,
    [s_Note_16]     NVARCHAR (255) NULL,
    [s_Note_17]     NVARCHAR (255) NULL,
    [s_Note_18]     NVARCHAR (255) NULL,
    [s_Note_19]     NVARCHAR (255) NULL,
    [s_Note_20]     NVARCHAR (255) NULL,
    [s_Note_21]     NVARCHAR (255) NULL,
    [s_Note_22]     NVARCHAR (255) NULL,
    [s_Note_23]     NVARCHAR (255) NULL,
    [s_Note_24]     NVARCHAR (255) NULL,
    [s_Note_25]     NVARCHAR (255) NULL,
    [s_Note_26]     NVARCHAR (255) NULL,
    [s_Note_27]     NVARCHAR (255) NULL,
    [s_Note_28]     NVARCHAR (255) NULL,
    [s_Note_29]     NVARCHAR (255) NULL,
    [s_Note_30]     NVARCHAR (255) NULL,
    [s_Note_31]     NVARCHAR (255) NULL,
    CONSTRAINT [PK_PR_Workers] PRIMARY KEY CLUSTERED ([s_ID] ASC),
    CONSTRAINT [FK_PR_Workers_LS_Employees] FOREIGN KEY ([s_Employee_ID]) REFERENCES [dbo].[LS_Employees] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

