CREATE TABLE [dbo].[rpt_Invoices] (
    [CPUID]          NVARCHAR (50)  NULL,
    [s_ID]           NVARCHAR (50)  DEFAULT (newid()) NOT NULL,
    [PreInvoiceID]   NVARCHAR (50)  NULL,
    [Inv_Date]       SMALLDATETIME  NULL,
    [Room_ID]        NVARCHAR (50)  NULL,
    [Object_ID]      NVARCHAR (50)  NULL,
    [Tax]            NVARCHAR (50)  NULL,
    [Total]          MONEY          NULL,
    [TotalUSD]       MONEY          NULL,
    [Curr]           NVARCHAR (50)  NULL,
    [Exchange]       MONEY          NULL,
    [Inwords]        NVARCHAR (100) NULL,
    [RedBill]        BIT            NULL,
    [Register_ID]    NVARCHAR (50)  NULL,
    [Payment_ID]     INT            NULL,
    [CaLV]           NVARCHAR (50)  NULL,
    [IsDebt]         BIT            NULL,
    [Company]        NVARCHAR (255) NULL,
    [AddressCompary] NVARCHAR (255) NULL,
    [Tax_Date]       SMALLDATETIME  NULL,
    [Employee_ID]    NVARCHAR (50)  NULL,
    [SohieuHD]       NVARCHAR (50)  NULL,
    [SoHD]           NVARCHAR (50)  NULL,
    [Pay]            MONEY          NULL,
    [PerDiscount]    FLOAT (53)     NULL,
    [AmountDiscount] MONEY          NULL,
    [Note]           NVARCHAR (255) NULL,
    [IDSort]         NUMERIC (18)   NOT NULL,
    [VND]            MONEY          NULL,
    [USD]            MONEY          NULL,
    [UCreate]        NVARCHAR (50)  NULL,
    [dtCreate]       SMALLDATETIME  NULL,
    [UEdit]          NVARCHAR (50)  NULL,
    [dtEdit]         SMALLDATETIME  NULL,
    [isSlipt]        BIT            NULL,
    PRIMARY KEY CLUSTERED ([s_ID] ASC)
);

