CREATE TABLE [dbo].[rpt_Register] (
    [CPUID]          NVARCHAR (50)  NULL,
    [Group_ID]       NVARCHAR (50)  NULL,
    [BK_ID]          NVARCHAR (50)  NULL,
    [s_ID]           NVARCHAR (50)  DEFAULT (newid()) NOT NULL,
    [Object_ID]      NVARCHAR (50)  NOT NULL,
    [Room_ID]        NVARCHAR (50)  NOT NULL,
    [PreRoomID]      NVARCHAR (50)  NULL,
    [PreRoom_ID]     NVARCHAR (50)  NULL,
    [From_date]      SMALLDATETIME  NULL,
    [To_date]        SMALLDATETIME  NULL,
    [CheckOut_Date]  SMALLDATETIME  NULL,
    [Price]          MONEY          NULL,
    [Serv]           FLOAT (53)     NULL,
    [Curr]           NVARCHAR (50)  NULL,
    [Discount]       FLOAT (53)     NULL,
    [Stat]           NVARCHAR (50)  NULL,
    [Pers]           SMALLINT       NULL,
    [Price_Extra]    MONEY          NULL,
    [Vat]            FLOAT (53)     NULL,
    [Payment]        INT            NULL,
    [TravelPermit]   NVARCHAR (50)  NULL,
    [Descr]          NVARCHAR (255) NULL,
    [CaLV]           NVARCHAR (50)  NULL,
    [PreRegister_ID] NVARCHAR (50)  NULL,
    [IsRegDay]       BIT            NULL,
    [DisMoney]       MONEY          NULL,
    [IDSort]         NUMERIC (18)   NOT NULL,
    [ObjectType_ID]  NVARCHAR (50)  NULL,
    [UCreate]        NVARCHAR (50)  NULL,
    [dtCreate]       SMALLDATETIME  NULL,
    [UEdit]          NVARCHAR (50)  NULL,
    [dtEdit]         SMALLDATETIME  NULL,
    [Note]           NVARCHAR (255) NULL,
    [b_Insert]       BIT            DEFAULT ((0)) NULL,
    [tmpToDate]      SMALLDATETIME  NULL,
    [BKArrange_ID]   NVARCHAR (50)  NULL,
    [CardID]         NVARCHAR (50)  NULL,
    [CardSerial]     NVARCHAR (50)  NULL,
    [Child]          INT            DEFAULT ((0)) NULL,
    [SegmID]         INT            NULL,
    [LimitID]        NVARCHAR (50)  NULL,
    [m_Balance]      MONEY          NULL,
    [Partner_ID]     NVARCHAR (50)  NULL,
    [listObjReg]     NVARCHAR (500) NULL,
    [ObjectName]     NVARCHAR (255) NULL,
    [s_Object_ID]    NVARCHAR (50)  NULL,
    [RoomType_ID]    NVARCHAR (50)  NULL,
    [Roomtype_Name]  NVARCHAR (255) NULL,
    [RoomID]         NVARCHAR (50)  NULL,
    [GroupName]      NVARCHAR (255) NULL,
    [ArrDate]        SMALLDATETIME  NULL,
    [DepDate]        SMALLDATETIME  NULL,
    [Phone]          NVARCHAR (50)  NULL,
    [IsTELCKCO]      BIT            NULL,
    [s_Nation_ID]    NVARCHAR (50)  NULL,
    [Nation_Name]    NVARCHAR (255) NULL,
    [Company]        NVARCHAR (255) NULL
);

