CREATE TABLE [dbo].[rpt_InvoiceDetail] (
    [s_ID]          NVARCHAR (50)  NULL,
    [Invoice_ID]    NVARCHAR (50)  NOT NULL,
    [Order_ID]      NVARCHAR (50)  NULL,
    [Services]      INT            NULL,
    [Emites]        NVARCHAR (50)  NULL,
    [Order_day]     SMALLDATETIME  NULL,
    [Sub_Total]     MONEY          NULL,
    [Total]         MONEY          NULL,
    [Curr]          NVARCHAR (50)  NULL,
    [PPV]           FLOAT (53)     NULL,
    [VAT]           FLOAT (53)     NULL,
    [TaxTTDB]       FLOAT (53)     NULL,
    [TaxOther]      FLOAT (53)     NULL,
    [Room_id]       NVARCHAR (50)  NULL,
    [FromDate]      SMALLDATETIME  NULL,
    [ToDate]        SMALLDATETIME  NULL,
    [NumDay]        SMALLINT       NULL,
    [Price]         MONEY          NULL,
    [Discount]      MONEY          NULL,
    [DiscountUSD]   MONEY          NULL,
    [Ext]           MONEY          NULL,
    [InvoiceChange] NVARCHAR (50)  NULL,
    [TotalUSD]      MONEY          NULL,
    [TotalVND]      MONEY          NULL,
    [PriceUSD]      MONEY          NULL,
    [ExtraUSD]      MONEY          NULL,
    [Note]          NVARCHAR (255) NULL,
    [IDSort]        NUMERIC (18)   NULL,
    [Register_ID]   NVARCHAR (50)  NULL,
    [isTax]         BIT            NULL,
    [Sub_TotalVND]  MONEY          NULL,
    [Sub_TotalUSD]  MONEY          NULL,
    CONSTRAINT [FK_rpt_InvoiceDetail_rpt_Invoices] FOREIGN KEY ([Invoice_ID]) REFERENCES [dbo].[rpt_Invoices] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

