CREATE TABLE [dbo].[rpt_Temp] (
    [CPUID] NVARCHAR (50)  NULL,
    [s1]    NVARCHAR (50)  NULL,
    [s2]    NVARCHAR (50)  NULL,
    [s3]    NVARCHAR (50)  NULL,
    [s4]    NVARCHAR (50)  NULL,
    [s5]    NVARCHAR (50)  NULL,
    [s6]    NVARCHAR (255) NULL,
    [s7]    NVARCHAR (255) NULL,
    [s8]    NVARCHAR (255) NULL,
    [s9]    NVARCHAR (255) NULL,
    [s10]   NVARCHAR (255) NULL,
    [s11]   NVARCHAR (255) NULL,
    [s12]   NVARCHAR (255) NULL,
    [s13]   NVARCHAR (255) NULL,
    [s14]   NVARCHAR (255) NULL,
    [s15]   NVARCHAR (255) NULL,
    [t1]    DATETIME       NULL,
    [t2]    DATETIME       NULL,
    [t3]    DATETIME       NULL,
    [t4]    DATETIME       NULL,
    [t5]    DATETIME       NULL,
    [v1]    MONEY          NULL,
    [v2]    MONEY          NULL,
    [v3]    MONEY          NULL,
    [v4]    MONEY          NULL,
    [v5]    MONEY          NULL,
    [f1]    FLOAT (53)     NULL,
    [f2]    FLOAT (53)     NULL,
    [f3]    FLOAT (53)     NULL,
    [f4]    FLOAT (53)     NULL,
    [f5]    FLOAT (53)     NULL
);

