CREATE TABLE [dbo].[rptDoanhthuThang] (
    [s_ID]        NVARCHAR (50)  DEFAULT (newid()) NOT NULL,
    [CPUID]       NVARCHAR (50)  NULL,
    [Ordinal]     INT            NULL,
    [dayMonth]    SMALLDATETIME  NULL,
    [Qty_Sup]     FLOAT (53)     NULL,
    [Price_Sup]   MONEY          NULL,
    [Total_Sup]   MONEY          NULL,
    [Qty_Delx]    FLOAT (53)     NULL,
    [Price_Delx]  MONEY          NULL,
    [Total_Delx]  MONEY          NULL,
    [Qty_Fam]     FLOAT (53)     NULL,
    [Price_Fam]   MONEY          NULL,
    [Total_Fam]   MONEY          NULL,
    [Qty_Sea]     FLOAT (53)     NULL,
    [Price_Sea]   MONEY          NULL,
    [Total_Sea]   MONEY          NULL,
    [Qty_VIP]     FLOAT (53)     NULL,
    [Price_VIP]   MONEY          NULL,
    [Total_VIP]   MONEY          NULL,
    [Qty_Stand]   FLOAT (53)     NULL,
    [Price_Stand] MONEY          NULL,
    [Total_Stand] MONEY          NULL,
    [Qty]         FLOAT (53)     NULL,
    [Price]       MONEY          NULL,
    [Total]       MONEY          NULL,
    [Per]         FLOAT (53)     NULL,
    [Note]        NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([s_ID] ASC)
);

