CREATE TABLE [dbo].[rptProductOrder] (
    [ID]           NVARCHAR (50)  NULL,
    [Store_Name]   NVARCHAR (255) NULL,
    [s_Store_ID]   NVARCHAR (50)  NULL,
    [Group_ID]     NVARCHAR (50)  NULL,
    [Product_ID]   NVARCHAR (255) NULL,
    [ProductKey]   NVARCHAR (50)  NULL,
    [Product_Name] NVARCHAR (255) NULL,
    [Unit]         NVARCHAR (50)  NULL,
    [Object_ID]    NVARCHAR (50)  NULL,
    [Exchange]     FLOAT (53)     CONSTRAINT [DF_rptProductOrder_Exchange] DEFAULT ((0)) NULL,
    [Price]        MONEY          NULL,
    [Qty]          FLOAT (53)     NULL,
    [QtyReturn]    FLOAT (53)     NULL,
    [s_Order_ID]   NVARCHAR (50)  NULL,
    [dt_OrderDate] SMALLDATETIME  NULL,
    [f_Discount]   FLOAT (53)     NULL,
    [m_Discount]   MONEY          NULL,
    [Total]        MONEY          NULL,
    [TotalOrder]   MONEY          NULL,
    [Store_Des]    NVARCHAR (255) NULL,
    [Store_DesID]  NVARCHAR (50)  NULL,
    [s_ItemID]     NVARCHAR (50)  NULL,
    [s_ItemName]   NVARCHAR (255) NULL,
    [f_VAT]        FLOAT (53)     NULL,
    [m_Balance]    MONEY          NULL,
    [m_Return]     MONEY          NULL,
    [s_EmployeeID] NVARCHAR (50)  NULL,
    [TotalImport]  MONEY          NULL,
    [s_ID]         NVARCHAR (50)  NULL,
    [MaNghiepvu]   NVARCHAR (50)  NULL,
    [f_Per]        FLOAT (53)     NULL
);

