CREATE TABLE [dbo].[rptRevenueInvoice] (
    [ID]              NVARCHAR (50)  NULL,
    [Invoice_ID]      NVARCHAR (50)  NULL,
    [Inv_Date]        DATETIME       NULL,
    [InvNum]          NVARCHAR (50)  NULL,
    [GuestName]       NVARCHAR (255) NULL,
    [Room]            NVARCHAR (50)  NULL,
    [RoomCharge]      MONEY          CONSTRAINT [DF_rptRevenueInvoice_RoomCharge] DEFAULT ((0)) NULL,
    [Minibar]         MONEY          CONSTRAINT [DF_rptRevenueInvoice_Minibar] DEFAULT ((0)) NULL,
    [Laundry]         MONEY          CONSTRAINT [DF_rptRevenueInvoice_Laundry] DEFAULT ((0)) NULL,
    [Massage]         MONEY          CONSTRAINT [DF_rptRevenueInvoice_Massage] DEFAULT ((0)) NULL,
    [TelephoneCharge] MONEY          CONSTRAINT [DF_rptRevenueInvoice_TelephoneCharge] DEFAULT ((0)) NULL,
    [Fax]             MONEY          CONSTRAINT [DF_rptRevenueInvoice_Fax] DEFAULT ((0)) NULL,
    [Restaurant]      MONEY          CONSTRAINT [DF_rptRevenueInvoice_Restaurant] DEFAULT ((0)) NULL,
    [Orther]          MONEY          CONSTRAINT [DF_Table_1_Exchange] DEFAULT ((0)) NULL,
    [TaxService]      MONEY          CONSTRAINT [DF_rptRevenueInvoice_TaxService] DEFAULT ((0)) NULL,
    [Total]           MONEY          CONSTRAINT [DF_rptRevenueInvoice_Total] DEFAULT ((0)) NULL,
    [CashPayment]     MONEY          CONSTRAINT [DF_rptRevenueInvoice_CashPayment] DEFAULT ((0)) NULL,
    [VAMCPayment]     MONEY          CONSTRAINT [DF_rptRevenueInvoice_VAMCPayment] DEFAULT ((0)) NULL,
    [OtherPayment]    MONEY          CONSTRAINT [DF_rptRevenueInvoice_OtherPayment] DEFAULT ((0)) NULL,
    [RoomTypeID]      NVARCHAR (50)  NULL,
    [RoomType_ID]     NVARCHAR (50)  NULL,
    [RoomType]        NVARCHAR (255) NULL,
    [Note]            NVARCHAR (500) NULL,
    [ServiceTypeID]   INT            NULL,
    [fromDate]        SMALLDATETIME  NULL,
    [toDate]          SMALLDATETIME  NULL,
    [Ext]             MONEY          NULL,
    [nDay]            FLOAT (53)     NULL,
    [Price]           MONEY          NULL,
    [Curr]            NVARCHAR (50)  NULL,
    [Room_ID]         NVARCHAR (50)  NULL,
    [RegNew_ID]       NVARCHAR (50)  NULL,
    [IsDebt]          BIT            NULL,
    [Register_ID]     NVARCHAR (50)  NULL
);

