CREATE TABLE [dbo].[rptRoomInfo] (
    [m_s_ID]       NVARCHAR (150) NULL,
    [Room_ID]      NVARCHAR (50)  NULL,
    [RoomType]     NVARCHAR (50)  NULL,
    [GroupName]    NVARCHAR (50)  NULL,
    [PriceVND]     MONEY          NULL,
    [PriceUSD]     MONEY          NULL,
    [fromDate]     DATETIME       NULL,
    [toDate]       DATETIME       NULL,
    [FullName]     NVARCHAR (50)  NULL,
    [IntCase]      INT            NULL,
    [BKID]         NVARCHAR (50)  NULL,
    [RegID]        NVARCHAR (50)  NULL,
    [IsRegDate]    BIT            NULL,
    [IsOver]       BIT            NULL,
    [CPUID]        NVARCHAR (50)  NULL,
    [Company]      NVARCHAR (150) NULL,
    [Row]          INT            NULL,
    [Col]          INT            NULL,
    [Note]         NVARCHAR (250) NULL,
    [NumPers]      INT            NULL,
    [PriceHVN]     MONEY          NULL,
    [PriceHUS]     MONEY          NULL,
    [isGroup]      BIT            NULL,
    [fRegID]       FLOAT (53)     NULL,
    [fBKID]        FLOAT (53)     NULL,
    [nRoomsBK]     INT            NULL,
    [nReg]         INT            NULL,
    [sGroupID]     NVARCHAR (150) NULL,
    [GroupID]      FLOAT (53)     NULL,
    [stat]         NVARCHAR (150) NULL,
    [Descr]        NVARCHAR (150) NULL,
    [phone]        NVARCHAR (150) NULL,
    [RoomtypeKey]  NVARCHAR (150) NULL,
    [BKArrange_ID] NVARCHAR (150) NULL
);

