CREATE TABLE [dbo].[tabcost] (
    [codedest] NVARCHAR (255) NULL,
    [name]     NVARCHAR (255) NULL,
    [type]     NVARCHAR (255) NULL,
    [mindig]   FLOAT (53)     NULL,
    [maxdig]   FLOAT (53)     NULL,
    [oper0]    FLOAT (53)     NULL,
    [oper1]    FLOAT (53)     NULL,
    [oper2]    FLOAT (53)     NULL,
    [oper3]    FLOAT (53)     NULL,
    [oper4]    FLOAT (53)     NULL,
    [oper5]    FLOAT (53)     NULL,
    [oper6]    FLOAT (53)     NULL,
    [oper7]    FLOAT (53)     NULL,
    [oper8]    FLOAT (53)     NULL,
    [oper9]    FLOAT (53)     NULL,
    [oper10]   FLOAT (53)     NULL,
    [oper11]   FLOAT (53)     NULL,
    [oper12]   FLOAT (53)     NULL,
    [oper13]   FLOAT (53)     NULL,
    [oper14]   FLOAT (53)     NULL,
    [oper15]   FLOAT (53)     NULL,
    [oper16]   FLOAT (53)     NULL,
    [oper17]   FLOAT (53)     NULL,
    [oper18]   FLOAT (53)     NULL,
    [oper19]   FLOAT (53)     NULL,
    [Zone]     INT            NULL
);

