CREATE TABLE [dbo].[tmp_ResOrderDetail_Ext] (
    [s_ID]                  NVARCHAR (50)  DEFAULT (newid()) NOT NULL,
    [OrderID]               NVARCHAR (50)  NULL,
    [ProName]               NVARCHAR (255) NULL,
    [Unit]                  NVARCHAR (50)  NULL,
    [Qty]                   FLOAT (53)     NULL,
    [Price]                 MONEY          NULL,
    [VAT]                   FLOAT (53)     NULL,
    [PPV]                   FLOAT (53)     NULL,
    [Discount]              FLOAT (53)     NULL,
    [Ordinal]               NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [s1]                    NVARCHAR (50)  NULL,
    [s2]                    NVARCHAR (50)  NULL,
    [s3]                    NVARCHAR (50)  NULL,
    [s4]                    NVARCHAR (50)  NULL,
    [v1]                    FLOAT (53)     NULL,
    [v2]                    FLOAT (53)     NULL,
    [v3]                    FLOAT (53)     NULL,
    [v4]                    FLOAT (53)     NULL,
    [Note]                  NVARCHAR (255) NULL,
    [mDiscount]             MONEY          NULL,
    [Vat_Amount]            MONEY          NULL,
    [PPV_Amount]            MONEY          NULL,
    [f_DiscountNumber]      FLOAT (53)     NULL,
    [m_DiscountNumber]      MONEY          NULL,
    [EndPrice]              MONEY          NULL,
    [SubTotal]              MONEY          NULL,
    [SubTotalNoneDisNumber] MONEY          NULL,
    [isBar]                 BIT            NULL,
    [isBep]                 BIT            NULL,
    [Employee_ID]           NVARCHAR (50)  NULL,
    [dtOrderTime]           SMALLDATETIME  NULL,
    PRIMARY KEY CLUSTERED ([s_ID] ASC),
    CONSTRAINT [FK_tmp_ResOrderDetail_Ext_tmpResOrder] FOREIGN KEY ([OrderID]) REFERENCES [dbo].[tmpResOrder] ([s_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

